src/basket/routes.py
"""
Blueprint for registration of delivery and inserting data to database
"""

import os

from flask import Blueprint, session, render_template, request, current_app, redirect

from sql_provider import SQLProvider
from usedatabase import work_with_db, insert_to_db
from basket.utils import add_seller, add_to_basket, clear_basket, clear_seller
from access import group_permission_decorator

provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))
basket_app = Blueprint('basket', __name__, template_folder='templates')


@basket_app.route('/', methods=['GET', 'POST'])
@group_permission_decorator
def choose_supplier():
    """
    Function gives the form for choosing supplier
    :return:
    """
    if request.method == 'GET':
        db_config = current_app.config['DB_CONFIG']
        SQL = provider.get('suppliers_list.sql')
        result2, schema2 = work_with_db(db_config, SQL)
        return render_template('suppliers.html', result=result2)

    name = request.form['name']
    items, _ = work_with_db(current_app.config['DB_CONFIG'], provider.get('get_supplier.sql', seller_id=name))
    print(items)

    add_seller(items)

    return redirect('/basket/list')


@basket_app.route('/list', methods=['GET', 'POST'])
@group_permission_decorator
def basket_list():
    """
    Function gives all products and your basket
    :return:
    """
    if request.method == 'GET':
        current_basket = session.get('basket', [])
        items = work_with_db(current_app.config['DB_CONFIG'], provider.get('all_products.sql'))
        print(items)
        print(current_basket)
        return render_template('basket_list.html', items=items[0], basket=current_basket)
    else:
        product_id = request.form['Product_id']
        items, _ = work_with_db(current_app.config['DB_CONFIG'],
                                provider.get('product_to_basket.sql', product_id=product_id))

        if items:
            add_to_basket(items)

        return redirect('/basket/list')


@basket_app.route('/buy')
def buy_handler():
    """
    Function inserts supply to db
    :return:
    """
    current_basket = session.get('basket', [])

    seller = session.get('seller', [])

    if current_basket:
        seller_id = seller[0]['seller_id']
        sql = provider.get('insert_to_supply.sql', seller_id=seller_id)
        db_config = current_app.config['DB_CONFIG']
        insert_to_db(db_config, sql)

        sql1 = provider.get('sort.sql')
        result, _ = work_with_db(db_config, sql1)
        supply_id = result[0]['supply_id']

        for i in current_basket:
            sql_i = provider.get('insert_to_supply_product.sql', supply_id=supply_id, product_id=i['Product_id'],
                                 S_Unit=i['Price'], S_Count=i['count'])
            insert_to_db(db_config, sql_i)

        for i in current_basket:
            sql_i2 = provider.get('insert_to_details.sql', amount=i['count'], Price=i['Price'],
                                  product_id=i['Product_id'])
            insert_to_db(db_config, sql_i2)

        clear_seller()
        clear_basket()

        return render_template('result.html', supply_id=supply_id)
    else:
        clear_seller()
        clear_basket()
        return render_template('basket_is_empty.html')


@basket_app.route('/clear-basket')
def clear_basket_handler():
    clear_basket()
    return redirect('/basket/list')


@basket_app.route('/clear')
def to_menu():
    clear_basket()
    clear_seller()
    return redirect('/')

src/basket/templates/basket_is_empty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }
    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

    <div class="container">
        <h1>Ошибка!</h1>
        <h2> Отсутствуют товары для поставки!</h2>

        <a type="submit" class="btn btn-dark" style="margin-top: 5px;  width:200px; text-align:center; margin: 0 auto" href="{{ url_for('menu') }}">В главное меню</a>
        <br clear="all">
        <a type="submit" class="btn btn-info" style="margin-top: 25px; margin-bottom:-10px width:100px; text-align:center; margin: 0 auto" href="{{ url_for('basket.basket_list') }}">Назад</a>
    </div>

</body>
</html>

src/basket/templates/basket_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <style>


        .heading{
            display: block;
            font-size: 35px;
            font-weight: 700;
            padding: 15px 0;
            border-bottom: 1px solid #f0f0f0;
            margin-bottom: 10px;
        }

        .usual{
            font-size: 25px;
        }


    </style>

</head>

<body>

{% import 'basket_utils.html' as utils %}

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">
    {% if session['seller'] %}
        <p style="font-size: 20px; margin-top:3px;">Поставщик: {{session.get('seller')[0]['Seller_name']}}</p>
    {% endif %}

    <div class="row">
        <div class="col-sm-5">
            <span class="heading"><font face="Times New Roman" color="#000000">Товары поставщика</font></span>
            {% if items %}
            {% for item in items %}
                {{ utils.render_item(item, show_form=True) }}
            {% endfor %}
            {% else %}
            <span class="heading"><font face="Times New Roman" color="#003300">Нет доступных товаров</font></span>
            {% endif %}
        </div>
        <div class="col-sm-5">
            <span class="heading"><font face="Times New Roman" color="#000000">Ваша корзина</font></span>
            {% if basket %}
            {% for item in basket %}
                {{ utils.render_item(item, show_form=False) }}
            {% endfor %}
            {% else %}
            <span class="usual"><font face="Times New Roman" color="#003300">Корзина пуста</font></span>
            {% endif %}
        </div>
        <div class="col-sm-2" >
            <div class="btn-group-vertical" >
                <a type="submit" class="btn btn-secondary" style="margin-bottom: 10px; margin-top: 20px; text-align:center" href=" {{ url_for('basket.clear_basket_handler') }}">Очистить корзину</a>
            <a type="submit" class="btn btn-success" style="margin-bottom: 10px; text-align:center" href=" {{ url_for('basket.buy_handler') }}">Оформить</a>
            <a type="submit" class="btn btn-dark" style="margin-bottom: 10px; text-align:center" href=" {{ url_for('basket.to_menu') }}">Вернуться в главное меню</a>
        </div>
    </div>
</div>
</div>

</body>

</html>

src/basket/templates/basket_utils.html
{% macro render_item(item, show_form=False) %}
<div class="card" style="width: 18rem; margin-bottom: 10px;">
    <p>
        <h5 class="card-title" style="text-align:center">{{ item['Product_name']}}</h5>
    <div class="card-body">
            <span><strong>Материал:</strong> {{ item['Material']}}</span>
            <br>
            <span><strong>Единица измерения:</strong> {{ item['Unit']}}</span>
            <br>
            <span><strong>Категория:</strong> {{ item['Category']}}</span>
            {% if item['count'] %}
                <br>
            <div style="text-align:center; font-size:20px; font-family: 'Times New Roman';">
                <span><strong>{{ item['count']}}</strong></span>
            </div>
            {% endif %}
    </div>

    </p>
    {% if show_form %}
    <div>
     <form action="" method="post" style="margin-bottom:10px; position:relative">
        <input type="hidden" name="Product_id" value="{{item['Product_id']}}">
         <input type="submit" style="position: relative; left: 50%; transform: translate(-50%, 0);"
                class="btn btn-primary"  value="Добавить в корзину">
    </form>
    </div>
    {% endif %}
</div>
{% endmacro %}

src/basket/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }
    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

    <div class="container">
        <h1>Поздравляем!</h1>
        <h2> Поставка №{{supply_id}} успешно оформлена!</h2>

        <a type="submit" class="btn btn-dark" style="margin-top: 10px; width:200px; text-align:center; margin: 0 auto" href="{{ url_for('menu') }}">В главное меню</a>

    </div>

</body>
</html>

src/basket/templates/suppliers.html
<!DOCTYPE html>
<html lang="en">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выбор поставщика</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .field_one, Back {
            width: 200px;
            margin: 0 auto;
            margin-bottom: 10px;
        }

        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }

        .seller {
            margin-bottom: 10px;
        }

    </style>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">


    <form class="seller" method="post" action="">

    <div class="field_one">
        <label for="exampleFormControlInput1" class="form-label">Выберите поставщика</label>
        <select class="form-select" id="exampleFormControlInput1" name="name">
            {% for i in result: %}
            <option value="{{i['seller_id']}}"> {{i['Seller_name']}} </option>
            {% endfor %}
        </select>

    </div>


    <button type="submit" class="btn btn-success" >Перейти к оформлению</button>

    </form>

    <a type="submit" class="btn btn-dark" style="margin-top: 10px; width:150px; text-align:center; margin: 0 auto" href="{{ url_for('menu') }}">В главное меню</a>

</div>

</body>
</html>