src/requests/routes.py
"""
Blueprint which shows implemented requests
"""

from flask import Blueprint, render_template, request, current_app

from access import group_permission_decorator
from sql_provider import SQLProvider
from usedatabase import work_with_db


request_app = Blueprint('requests', __name__, template_folder='templates')

provider = SQLProvider('requests/sql')


@request_app.route('/')
@group_permission_decorator
def request_menu():
    return render_template('requests.html')


@request_app.route('/first', methods=['GET', 'POST'])
@group_permission_decorator
def first():
    """
    Function gives result of the first SQL request
    :return:
    """
    if request.method == 'GET':
        return render_template('one_request.html')
    else:
        name = request.form['name']
        sql = provider.get('request_one.sql', name=name)
        db_config = current_app.config['DB_CONFIG']
        result, schema = work_with_db(db_config, sql)
        context = {'schema': schema, 'data': result}
        if result:
            return render_template('request_one_table.html', context=context)
        else:
            return render_template('result_is_empty.html')


@request_app.route('/second', methods=['GET', 'POST'])
@group_permission_decorator
def second():
    """
    Function gives result of the second SQL request
    :return:
    """
    db_config = current_app.config['DB_CONFIG']
    if request.method == 'GET':
        SQL = provider.get('suppliers.sql')
        result2, schema2 = work_with_db(db_config, SQL)
        return render_template('two_request.html', result=result2)

    name = request.form['name']
    year = request.form['year']

    print(name)
    print(year)

    sql = provider.get('request_two.sql', name=name, year=year)

    result1, schema1 = work_with_db(db_config, sql)

    context = {'schema': schema1, 'data': result1}

    print(context)

    if result1:
        return render_template('request_two_table.html', context=context)
    else:
        return render_template('result_is_empty.html')


@request_app.route('/third', methods=['GET', 'POST'])
@group_permission_decorator
def third():
    """
    Function gives result of the third SQL request
    :return:
    """
    if request.method == 'GET':
        return render_template('three_request.html')

    name = request.form['name']
    sql = provider.get('request_three.sql', name = name)
    db_config = current_app.config['DB_CONFIG']
    result, schema = work_with_db(db_config, sql)

    context = {'schema': schema, 'data': result}

    if result:
        return render_template('request_three_table.html', context=context)
    else:
        return render_template('result_is_empty.html')


@request_app.route('/fourth', methods=['GET', 'POST'])
@group_permission_decorator
def fourth():
    """
    Function gives result of the fourth SQL request
    :return:
    """
    if request.method == 'GET':
        return render_template('four_request.html')
    
    year = request.form['year']
    sql = provider.get('request_four.sql', year=year)
    db_config = current_app.config['DB_CONFIG']
    result, schema = work_with_db(db_config, sql)
    context = {'schema': schema, 'data': result}

    if result:
        return render_template('request_four_table.html', context=context)
    else:
        return render_template('result_is_empty.html')

src/requests/templates/four_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Запрос 4</title>
    <style>
        .field, Back {
            width: 200px;
            margin: 0 auto;
        }
        .container {
            text-align: center;
            transform: translateY(20%);
            display: flex;
            flex-direction: column;
        }
        .product {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">
   <form class="product" method="POST" action="{{ url_for('requests.fourth') }}">

    <div class="field">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Введите год</label>
            <input type="text" class="form-control" name="year" id="exampleFormControlInput1" required>
        </div>

    </div>

    <button type="submit" class="btn btn-success" >Получить информацию</button>

    </form>
    <div class="Back">
        <a type="submit" class="btn btn-dark" href="{{ url_for('requests.request_menu') }}">Назад</a>
    </div>

</div>

</body>
</html>

src/requests/templates/one_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Запрос 1</title>
    <style>
        .field, Back {
            width: 200px;
            margin: 0 auto;
        }
        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }
        .product {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">
   <form class="product" method="POST" action="">

    <div class="field">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Введите название товара</label>
            <input type="text" class="form-control" name="name" id="exampleFormControlInput1" required>
        </div>

    </div>

    <button type="submit" class="btn btn-success" >Получить информацию</button>

    </form>
    <div class="Back">
        <a type="submit" class="btn btn-dark" href="{{ url_for('requests.request_menu') }}">Назад</a>
    </div>

</div>

</body>
</html>

src/requests/templates/request_four_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Список заказов</title>
</head>

<style>
    .table_wh {

        margin: 0 auto;
        margin-left: 200px;
        margin-right: 200px;
        margin-bottom: 50px;
    }

    .buttons {
        width: 200px;
        margin: 0 auto;

    }

    .container {
            text-align: center;
            transform: translateY(30%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
    }
    td {
        width: 100px
    }
</style>

<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">

<div class="table_wh">
    <table class = "table">


        <tr class="table-primary">
            <th scope="col">Название товара</th>

<!--            {% for item in context['schema'] %}-->
<!--                <td> {{ item }} </td>-->
<!--            {% endfor %}-->
        </tr>
        {% for dictionary in context['data'] %}
            <tr class="table-secondary">
                {% for value in dictionary.values() %}
                    <td> {{ value }} </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>

        <div class="buttons">
            <a type="submit" class="btn btn-dark" style="margin-bottom: 10px" href="{{ url_for('requests.fourth') }}">Назад</a>
<!--        <form method="GET" action="{{ url_for('requests.first') }}">-->
<!--            <button type="submit">Назад</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary" style="margin-bottom: 10px" href="{{ url_for('requests.request_menu') }}">Выход в меню запросов</a>
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary"  href="{{ url_for('exit') }}">Завершить работу</a>
<!--        <form method="GET" action="{{ url_for('exit') }}">-->
<!--            <button type="submit">Завершить работу</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
    </div>

</div>


</body>
</html>

src/requests/templates/request_one_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Список заказов</title>
</head>

<style>
    .table_wh {

        margin: 0 auto;
        margin-left: 200px;
        margin-right: 200px;
        margin-bottom: 50px;
    }

    .buttons {
        width: 200px;
        margin: 0 auto;

    }

    .container {
            text-align: center;
            transform: translateY(30%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
    }
    td {
        width: 100px
    }
</style>

<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">

<div class="table_wh">
    <table class = "table">


        <tr class="table-primary">
            <th scope="col">Шифр</th>
            <th scope="col">Название</th>
            <th scope="col">Единица измерения</th>
            <th scope="col">Цена единицы</th>
            <th scope="col">Количество на складе</th>
            <th scope="col">Дата последнего изменения количества</th>
<!--            {% for item in context['schema'] %}-->
<!--                <td> {{ item }} </td>-->
<!--            {% endfor %}-->
        </tr>
        {% for dictionary in context['data'] %}
            <tr class="table-secondary">
                {% for value in dictionary.values() %}
                    <td> {{ value }} </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>

        <div class="buttons">
            <a type="submit" class="btn btn-dark" style="margin-bottom: 10px" href="{{ url_for('requests.first') }}">Назад</a>
<!--        <form method="GET" action="{{ url_for('requests.first') }}">-->
<!--            <button type="submit">Назад</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary" style="margin-bottom: 10px" href="{{ url_for('requests.request_menu') }}">Выход в меню запросов</a>
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary"  href="{{ url_for('exit') }}">Завершить работу</a>
<!--        <form method="GET" action="{{ url_for('exit') }}">-->
<!--            <button type="submit">Завершить работу</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
    </div>

</div>


</body>
</html>

src/requests/templates/request_three_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Список заказов</title>
</head>

<style>
    .table_wh {

        margin: 0 auto;
        margin-left: 200px;
        margin-right: 200px;
        margin-bottom: 50px;
    }

    .buttons {
        width: 200px;
        margin: 0 auto;

    }

    .container {
            text-align: center;
            transform: translateY(30%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
    }
    td {
        width: 100px
    }
</style>

<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="4"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="4"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">

<div class="table_wh">
    <table class = "table">


        <tr class="table-primary">
            <th scope="col">Поставщик</th>
            <th scope="col">Цена товара</th>

<!--            {% for item in context['schema'] %}-->
<!--                <td> {{ item }} </td>-->
<!--            {% endfor %}-->
        </tr>
        {% for dictionary in context['data'] %}
            <tr class="table-secondary">
                {% for value in dictionary.values() %}
                    <td> {{ value }} </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>

        <div class="buttons">
            <a type="submit" class="btn btn-dark" style="margin-bottom: 10px" href="{{ url_for('requests.third') }}">Назад</a>
<!--        <form method="GET" action="{{ url_for('requests.first') }}">-->
<!--            <button type="submit">Назад</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary" style="margin-bottom: 10px" href="{{ url_for('requests.request_menu') }}">Выход в меню запросов</a>
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary"  href="{{ url_for('exit') }}">Завершить работу</a>
<!--        <form method="GET" action="{{ url_for('exit') }}">-->
<!--            <button type="submit">Завершить работу</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
    </div>

</div>


</body>
</html>

src/requests/templates/request_two_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Список заказов</title>
</head>

<style>
    .table_wh {

        margin: 0 auto;
        margin-left: 200px;
        margin-right: 200px;
        margin-bottom: 50px;
    }

    .buttons {
        width: 200px;
        margin: 0 auto;

    }

    .container {
            text-align: center;
            transform: translateY(30%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
    }
    td {
        width: 100px
    }
</style>

<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">

<div class="table_wh">
    <table class = "table">


        <tr class="table-primary">
            <th scope="col">Шифр</th>
            <th scope="col">Название</th>
            <th scope="col">Поставщик</th>
<!--            {% for item in context['schema'] %}-->
<!--                <td> {{ item }} </td>-->
<!--            {% endfor %}-->
        </tr>
        {% for dictionary in context['data'] %}
            <tr class="table-secondary">
                {% for value in dictionary.values() %}
                    <td> {{ value }} </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>

        <div class="buttons">
            <a type="submit" class="btn btn-dark" style="margin-bottom: 10px" href="{{ url_for('requests.second') }}">Назад</a>
<!--        <form method="GET" action="{{ url_for('requests.first') }}">-->
<!--            <button type="submit">Назад</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary" style="margin-bottom: 10px" href="{{ url_for('requests.request_menu') }}">Выход в меню запросов</a>
<!--        <br clear="all" />-->
            <a type="submit" class="btn btn-primary"  href="{{ url_for('exit') }}">Завершить работу</a>
<!--        <form method="GET" action="{{ url_for('exit') }}">-->
<!--            <button type="submit">Завершить работу</button>-->
<!--        </form>-->
<!--        <br clear="all" />-->
    </div>

</div>


</body>
</html>

src/requests/templates/requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Меню запросов</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        div.buttons {
            width: 550px;
            margin: 0 auto;
            text-align: center;
            display: flex;
            flex-direction: column;
        }
        h2 {
            font-family: "Times New Roman";
            text-align: center;
            display: flex;
            flex-direction: column;
        }

        .container {
            width: 600px;
            top: 30%;
            transform: translateY(20%);
            text-align: center;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>


<div class="container">
    <h2>Выберите, пожалуйста, услугу</h2>
    <div class="buttons">
        <a type="submit" class="btn btn-primary" style="margin-bottom: 10px; text-align: left; font-family: 'Times New Roman'" href="{{ url_for('requests.first') }}">Показать отчет о запасах товара XXX на складе</a>
        <a type="submit" class="btn btn-primary" style="margin-bottom: 10px; text-align: left; font-family: 'Times New Roman'" href="{{ url_for('requests.second') }}">Показать шифры и названия товаров, которые поставщик XXX поставил в XXX году</a>
        <a type="submit" class="btn btn-primary" style="margin-bottom: 10px; text-align: left; font-family: 'Times New Roman'" href="{{ url_for('requests.third') }}">Показать поставщика самого дешевого товара с названием XXX</a>
        <a type="submit" class="btn btn-primary" style="margin-bottom: 10px; text-align: left; font-family: 'Times New Roman'" href="{{ url_for('requests.fourth') }}">Показать название товара, который ни разу не поставлялся в XXX году</a>
        <a type="submit" class="btn btn-primary" style="margin-bottom: 10px; font-family: 'Times New Roman'" href="{{ url_for('menu') }}">Выход в главное меню</a>
    </div>


    </div>

</body>
</html>

src/requests/templates/result_is_empty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }
    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px; ">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

    <div class="container">
        <h1>Просим прощения!</h1>
        <h2> Результатов по вашему запросу не найдено!</h2>

        <a type="submit" class="btn btn-dark" style="margin-top: 10px; width:200px; text-align:center; margin: 0 auto" href="{{ url_for('menu') }}">В главное меню</a>
        <a type="submit" class="btn btn-dark" style="margin-top: 10px; width:200px; text-align:center; margin: 0 auto" href="{{ url_for('requests.request_menu') }}">В меню запросов</a>
    </div>

</body>
</html>

src/requests/templates/three_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Запрос 3</title>
    <style>
        .field, Back {
            width: 200px;
            margin: 0 auto;
        }
        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }
        .product {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">
   <form class="product" method="POST" action="{{ url_for('requests.third') }}">

    <div class="field">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Введите название товара</label>
            <input type="text" class="form-control" name="name" id="exampleFormControlInput1" required>
        </div>

    </div>

    <button type="submit" class="btn btn-success" >Получить информацию</button>

    </form>
    <div class="Back">
        <a type="submit" class="btn btn-dark" href="{{ url_for('requests.request_menu') }}">Назад</a>
    </div>

</div>

</body>
</html>

src/requests/templates/two_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Запрос 2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .field_one, Back {
            width: 200px;
            margin: 0 auto;
        }

        .container {
            text-align: center;
            transform: translateY(20%);
            font-family: "Times New Roman";
            display: flex;
            flex-direction: column;
        }

        .seller {
            margin-bottom: 10px;
        }

    </style>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #0099FF; height:50px;">
  <!-- Navbar content -->
    <p style="margin-left: 10px;"><font size="5"; color="white">Информационная система «Склад»</font></p>

    {% if session['group_name'] == guest %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы не авторизовались</font></p>
    {% else %}
        <p style="text-align:right; margin-right: 10px;"><font size="3"; color="white">Вы авторизованы как {{session['group_name']}}</font></p>
    {% endif %}


</nav>

<div class="container">
    <form class="seller" method="POST" action="">

    <div class="field_one">
        <label for="exampleFormControlInput2" class="form-label">Выберите поставщика</label>
        <select class="form-select" aria-label="Default select example" id="exampleFormControlInput2" name="name">
            {% for i in result: %}
            <option value={{i['Seller_name']}} >{{i['Seller_name']}}</option>
            {% endfor %}
        </select>

    </div>

    <div class="field_one">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Введите год поставки</label>
            <input type="text" class="form-control" name="year" id="exampleFormControlInput1" required>
        </div>

    </div>

    <button type="submit" class="btn btn-success" >Получить информацию</button>

    </form>
   <div class="Back">
        <a type="submit" class="btn btn-dark" href="{{ url_for('requests.request_menu') }}">Назад</a>
   </div>

</div>

</body>
</html>